name: "Test Extractor"
description: >-
  Extract test results, coverage results, code quality
  results and metadata to be piped to other CI steps
author: "kirinnee"
inputs:
  data:
    required: true
    description: "Data search configuration. See [Input](#input-schema)"
    default: "[]"
runs:
  using: "node16"
  main: "dist/index.js"
